name: Autorelease

on:
  push:
    branches:
      - main
      - master
    tags:
      - 'v*'
  pull_request:
  repository_dispatch:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  autorelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: jdx/mise-action@v2

      - name: Install
        run: mise run install

      - name: Codegen
        run: mise run codegen

      - name: Check for changes
        id: git-check
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Create PR if changes
        if: steps.git-check.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update generated code"
          title: "chore: update generated code"
          body: "Automated PR to update generated code."
          branch: "chore/codegen-update"
          base: ${{ github.head_ref || github.ref }}

      - name: CI
        run: mise run ci

      - name: Release
        if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'repository_dispatch'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create ${{ github.ref_name }} --generate-notes

      - name: Upload Artifacts
        if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'repository_dispatch'
        uses: actions/upload-artifact@v4
        with:
          name: source
          path: |
            .
            !./.git/**
            !./node_modules/**
            !./.mise/**
            !./coverage/**
            !./build/**
            !./dist/**
